config/routes.rb
MehdiApp::Application.routes.draw do
  devise_for :users

  resources :repairs

  resources :issues

  resources :posts

  match '/repairs', :to =>'repairs#index'
  root :to => 'repairs#index'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  
  validates :name, :email, :location, :issue, :presence => true
  validates :email, :uniqueness => true
  validates :number, :length => { :is => 10 }
  
  scope :oncampus,
    where('oncampus = ?', true)
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all
#    @repairs = Repair.oncampus

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repairs }
    end
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
    @repair = Repair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repair }
    end
  end

  # GET /repairs/new
  # GET /repairs/new.json
  def new
    @repair = Repair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repair }
    end
  end

  # GET /repairs/1/edit
  def edit
    @repair = Repair.find(params[:id])
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(params[:repair])

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render json: @repair, status: :created, location: @repair }
      else
        format.html { render action: "new" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repairs/1
  # PUT /repairs/1.json
  def update
    @repair = Repair.find(params[:id])

    respond_to do |format|
      if @repair.update_attributes(params[:repair])
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair = Repair.find(params[:id])
    @repair.destroy

    respond_to do |format|
      format.html { redirect_to repairs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table>
  <tr>
    <th>Day</th>
    <th>Name</th>
    <th>Email</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.day %></td>
    <td><%= issue.name %></td>
    <td><%= issue.email %></td>
    <td><%= issue.number %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @issue.day %>
</p>

<p>
  <b>Name:</b>
  <%= @issue.name %>
</p>

<p>
  <b>Email:</b>
  <%= @issue.email %>
</p>

<p>
  <b>Number:</b>
  <%= @issue.number %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MehdiApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">
  
</head>
<body>

<% if alert %>
<div class="alert alert-error">
<%= alert %>
</div>
<% end %>
<% if notice %>
<div class="alert alert-success">
<%= notice %>
</div>
<% end %>

<%= yield %>

<div align="center">
	<% if user_signed_in? %>
	<li><%= link_to 'Logout',
	destroy_user_session_path,
	method: :delete %></li>
<% end %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

  

app/views/repairs/_form.html.erb
<%= form_for(@repair) do |f| %>
  <% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% @repair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Date" %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "On Campus?" %><br />
    <%= f.check_box :oncampus %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label "Device Type" %><br />
    <%= f.radio_button(:device, :desktop) %>
    <%= f.label(:device_desktop, "Desktop") %>
    <%= f.radio_button(:device, :laptop) %>
    <%= f.label(:device_laptop, "Laptop") %>
    <%= f.radio_button(:device, :mobile) %>
    <%= f.label(:device_mobile, "Mobile") %>
    <%= f.radio_button(:device, :ipad) %>
    <%= f.label(:device_ipad, "iPad/eReader") %>
    <%= f.radio_button(:device, :other) %>
    <%= f.label(:device_other, "Other") %>
  </div>
  <div class="field">
    <%= f.label "Operating System" %><br />
    <%= f.collection_select(:opsystem, [:windows, :mac, :android, :ios, :blackberry, :other], :to_s, :to_s) %>
  </div>
  <div class="field">
    <%= f.label :issue %><br />
    <%= f.text_area :issue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/repairs/edit.html.erb
<h1>Editing repair</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair %> |
<%= link_to 'Back', repairs_path %>

app/views/repairs/index.html.erb
<title>FixIT Philadelphia</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">
  <script src="javascripts/modernizr.foundation.js"></script>

<div style="background-color: #FFFFFF">

 <div class="fixed">
  <nav class="top-bar">
    <ul>
      <!-- Title Area -->
      <li class="name">
        <h1>
          <a href="#">
            FixIT Philadelphia
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>
 
    <section>
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="divider"></li>
        <li><a href="#">Created by Mehdi Charfi</a></li>
        <li class="divider"></li>
        
      </ul>
    </section>
  </nav>
  </div>
 

<br><br><br>

<div class="row">
    <div class="twelve columns">
      <h1>Welcome to FixIT Philadelphia</h1>
      <p><i><strong>If it ain't broke, don't fix it. But if it is, we'll be happy to help!</strong></i></p>
      <hr />
    </div>
  </div>
  
<div class="row">
    <div class="eight columns">
    <br><br>	
    <center><img width=500 src="http://4.bp.blogspot.com/-6mAp2NnjU64/UUfnYm6mYhI/AAAAAAAAAKM/QWiGlNP_7kM/s1600/steallr.jpg"><br><br>
     <h3>Get Tech Support Now!</h3></center>

      <!-- Grid Example -->
      <div class="row">
        <div class="twelve columns">
          <div class="panel">
            <p>Get tech support for: Windows and Mac Operating Systems, Microsoft Office, Virus problems, Internet security, Email problems, iTunes, and much more.</p>
          </div>
        </div>
      </div>
      
<center><h4>→  <%= link_to 'Click Here to Create a New Repair', new_repair_path %>  ←</h4></center>

    </div>

    <div class="four columns">
      <h4>About FixIT</h4>
      <p>FixIT makes it easy for anyone to get tech support from anywhere on campus within 24 hours. The first service of its kind, FixIT charges 50¢ per-minute, making it easy for you to get the help you need no matter what the problem is. And, because we believe in our service so much, if we can't help you, not only is our service free, but we can offer you advice on how to get it fixed.</p>
      <p>Our support staff has both the passion and expertise to help you fix your tech issue, regardless of the problem you are experiencing. Software issues? Internet not connecting? Have a virus? Need to organize your photos on your computer or online? Need help setting up a social networking page, or with Google's online tools? We can do that too. Give us a try, your first five minutes are free. There is nothing to lose.</p>
	  <p><img src="http://fraudavengers.org/wp-content/uploads/2011/10/MultipleTechDevices.jpg"></p>
    </div>
  </div>
      
<center>

<div id="display">
  <div class="row">
        <div class="twelve columns">
          
<center>      
<h3>Repair Queue</h3>

<table style="vertical-align:middle">
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Email</th>
    <th>Number</th>
    <th>On Campus?</th>
    <th>Location</th>
    <th>Device</th>
    <th>OS</th>
    <th>Issue</th>
    <th></th>
    <th></th>
  </tr>

<% @repairs.each do |repair| %>
  <tr>
    <td><center><%= repair.day %></center></td>
    <td><center><%= repair.name %></center></td>
    <td><center><%= repair.email %></center></td>
    <td><center><%= repair.number %></center></td>
    <td><center><%= repair.oncampus %></center></td>
    <td><center><%= repair.location %></center></td>
    <td><center><%= repair.device %></center></td>
    <td><center><%= repair.opsystem %></center></td>
    <td><center><%= repair.issue %></center></td>
    <td><center><%= link_to 'Edit', edit_repair_path(repair) %></center></td>
    <td><center><%= link_to 'Delete', repair, confirm: 'Are you sure that you want to delete this repair?', method: :delete %></center></td>
  </tr>
<% end %>
</table>
</center>
<br />
    
	</div>
    </div>
    
        </div>
    
    <div id="button">
    <button style="font-weight: bold">Show/Hide Repair Queue</button>
    </div>
</center>
    
<br>
<div align="center"><strong>© 2013 Mehdi Charfi. All rights reserved.</strong></center></div><br>
</div>

  <script src="javascripts/jquery.js"></script>
  <script src="javascripts/foundation.min.js"></script>
  
  <!-- Initialize JS Plugins -->
  <script src="javascripts/app.js"></script>

  
    <script>
    $(window).load(function(){
      $("#featured").orbit();
    });
    </script> 

app/views/repairs/new.html.erb
<h1>New repair</h1>

<%= render 'form' %>

<%= link_to 'Back', repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @repair.day %>
</p>

<p>
  <b>Name:</b>
  <%= @repair.name %>
</p>

<p>
  <b>Email:</b>
  <%= @repair.email %>
</p>

<p>
  <b>Number:</b>
  <%= @repair.number %>
</p>

<p>
  <b>On-campus:</b>
  <%= @repair.oncampus %>
</p>

<p>
  <b>Location:</b>
  <%= @repair.location %>
</p>

<p>
  <b>Device:</b>
  <%= @repair.device %>
</p>

<p>
  <b>OpSystem:</b>
  <%= @repair.opsystem %>
</p>

<p>
  <b>Issue:</b>
  <%= @repair.issue %>
</p>


<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>